### ISSUE TITLE
Package does not have tarball included in release assets, and thus not available in roc-start

### ISSUE THREAD

**Issue by imclerran** [lukewilliamboswell/roc-random#4]
Package is not available in [roc-start](https://github.com/imclerran/roc-start) CLI tool, due to missing tarball in 0.2.0 release.

I see that hasnep/bundle-roc-library is already in the repo workflows, ~so a simple re-release should be all it takes for roc-random to be available in roc-start.~

EDIT:
Just took a look at the workflow results from the last time bundle.yaml ran, and I see that roc build —bundle failed. Don’t know if that’s a known issue with roc bundle, but looks like this issue isn’t as simple as I first thought.. 😅

**Comment by imclerran** [comment]
Just took a look at the workflow results from the last time bundle.yaml ran, and I see that `roc build —bundle` failed. Don’t know if that’s a known issue with roc bundle, but looks like this issue isn’t as simple as I first thought.. 😅

**Comment by imclerran** [comment]
The error message from `roc build` says it panicked at tarball.rs line 273, which is currently in the middle of a comment block. Looks like maybe it would be the todo() at 278, in which case it would be a problem in parsing a .roc header.

**Comment by imclerran** [comment]
So I was able to clone the repo locally and run `roc build --bundle .tar.br package/main.roc` without issue.

Looks like re-running the workflow may work now, or you could bundle on your local machine and upload manually. Once that tarball is on the release assets, roc-random will be available in roc-start!

**Comment by lukewilliamboswell** [comment]
Made a new release. Looks like the bundle succeeded this time. Thank you for the reminder
